import { Anton } from "next/font/google"; // import Anton font
import "./globals.css";

// Initialize Anton
const anton = Anton({
  subsets: ["latin"],
  weight: "400", // Anton only has 400 weight
  variable: "--font-anton",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${anton.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
